/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Tipografias.Fuentes;
import static java.awt.GridBagConstraints.BOTH;

/**
 *
 * @author EMmanuel
 */


public class InicializacionMain extends javax.swing.JFrame {

    /**
     * Creates new form InicioMain
     */
    Fuentes tipoFuente;
    public InicializacionMain() {
        initComponents();
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        tipoFuente= new Fuentes();
        jLNombreJuego.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 83));
        //jLTBienvenida.setFont(tipoFuente.fuente(tipoFuente.CLEAR, 1, 45));
        jLCargando.setFont(tipoFuente.fuente(tipoFuente.NINE, 1, 45));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombreJuego = new javax.swing.JLabel();
        jLTBienvenida = new javax.swing.JLabel();
        jLCargando = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombreJuego.setBackground(new java.awt.Color(153, 0, 102));
        jLNombreJuego.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 80)); // NOI18N
        jLNombreJuego.setForeground(new java.awt.Color(255, 255, 255));
        jLNombreJuego.setText("BUBBLE-BLIP");
        getContentPane().add(jLNombreJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLTBienvenida.setFont(new java.awt.Font("Consolas", 0, 40)); // NOI18N
        jLTBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jLTBienvenida.setText("BIENVENIDO A");
        getContentPane().add(jLTBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLCargando.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLCargando.setForeground(new java.awt.Color(255, 255, 255));
        jLCargando.setText("CARGANDO......");
        getContentPane().add(jLCargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(41, 245, 226));
        jProgressBar1.setForeground(new java.awt.Color(41, 245, 226));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 380, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Inicializaciòn800x457.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicializacionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicializacionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicializacionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicializacionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicializacionMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCargando;
    private javax.swing.JLabel jLNombreJuego;
    private javax.swing.JLabel jLTBienvenida;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
