/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Tipografias.Fuentes;

/**
 *
 * @author abiga
 */
public class MenuMain extends javax.swing.JFrame {

    /**
     * Creates new form MenuMain
     */
    Fuentes tipoFuente;
    public MenuMain() {
        initComponents();
        tipoFuente= new Fuentes();
        BotonMC.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 34));
        BotonMR.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 34));
        BotonConfi.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 34));
        BotonAD.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 34));
        jLNombreJuego.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 74));       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonMC = new javax.swing.JButton();
        BotonMR = new javax.swing.JButton();
        BotonConfi = new javax.swing.JButton();
        BotonAD = new javax.swing.JButton();
        jLNombreJuego = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonMC.setForeground(new java.awt.Color(255, 255, 255));
        BotonMC.setText("MODO CLÁSICO");
        BotonMC.setBorderPainted(false);
        BotonMC.setContentAreaFilled(false);
        getContentPane().add(BotonMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 200, 50));

        BotonMR.setForeground(new java.awt.Color(255, 255, 255));
        BotonMR.setText("MODO RETO");
        BotonMR.setBorderPainted(false);
        BotonMR.setContentAreaFilled(false);
        BotonMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMRActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 200, 50));

        BotonConfi.setForeground(new java.awt.Color(255, 255, 255));
        BotonConfi.setText("CONFIGURACIÓN");
        BotonConfi.setBorderPainted(false);
        BotonConfi.setContentAreaFilled(false);
        getContentPane().add(BotonConfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 200, 50));

        BotonAD.setForeground(new java.awt.Color(255, 255, 255));
        BotonAD.setText("ACERCA DE");
        BotonAD.setBorderPainted(false);
        BotonAD.setContentAreaFilled(false);
        BotonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonADActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 200, 60));

        jLNombreJuego.setForeground(new java.awt.Color(255, 255, 255));
        jLNombreJuego.setText("BUBBLE-BLIP");
        getContentPane().add(jLNombreJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menù800x457.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonADActionPerformed
        // TODO add your handling code here:
        
        AcercaDeMain obj = new AcercaDeMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotonADActionPerformed

    private void BotonMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMRActionPerformed
        // TODO add your handling code here:
        
        ModoRetoMain obj = new ModoRetoMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotonMRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAD;
    private javax.swing.JButton BotonConfi;
    private javax.swing.JButton BotonMC;
    private javax.swing.JButton BotonMR;
    private javax.swing.JLabel jLNombreJuego;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
