/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Tipografias.Fuentes;

/**
 *
 * @author abiga
 */
public class ModoRetoMain extends javax.swing.JFrame {

    /**
     * Creates new form ModoRetoMain
     */
    
    Fuentes tipoFuente;
    public ModoRetoMain() {
        initComponents();
        tipoFuente= new Fuentes();
        //Fuente texto de instrucciones
        jLInstruccion1.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        jLInstruccion2.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        jLInstruccion3.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        //Fuente texto error
        jLMensajeError.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 18));
        //Fuente texto botones
        BotonSalir.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 40));
        BotonMenu.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 40));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLInstruccion1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        jLMensajeError = new javax.swing.JLabel();
        jTxtEscribir = new javax.swing.JTextField();
        jLInstruccion2 = new javax.swing.JLabel();
        jLInstruccion3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/corazonT50x50.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 170, 20));

        jLInstruccion1.setForeground(new java.awt.Color(0, 74, 173));
        jLInstruccion1.setText("Traduce la palabra");
        jPanel1.add(jLInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 170, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BPausa60x60.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, 80));

        BotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalir.setForeground(new java.awt.Color(31, 19, 71));
        BotonSalir.setText("SALIR");
        BotonSalir.setToolTipText("");
        BotonSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonSalir.setBorderPainted(false);
        BotonSalir.setContentAreaFilled(false);
        BotonSalir.setDefaultCapable(false);
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 140, 50));

        BotonMenu.setForeground(new java.awt.Color(31, 19, 71));
        BotonMenu.setText("MENÚ");
        BotonMenu.setBorderPainted(false);
        BotonMenu.setContentAreaFilled(false);
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 140, 50));
        jPanel1.add(jLMensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 390, 280, 30));

        jTxtEscribir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTxtEscribir.setBorder(null);
        jTxtEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEscribirActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtEscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 220, 40));

        jLInstruccion2.setForeground(new java.awt.Color(0, 74, 173));
        jLInstruccion2.setText("del meteorito");
        jPanel1.add(jLInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        jLInstruccion3.setForeground(new java.awt.Color(0, 74, 173));
        jLInstruccion3.setText("al inglés");
        jPanel1.add(jLInstruccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonS_60x142.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 150, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonM_60x141.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 140, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Modo reto 800x457.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEscribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEscribirActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        
        MenuMain obj = new MenuMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        
        MenuMain obj = new MenuMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotonMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoRetoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoRetoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoRetoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoRetoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoRetoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLInstruccion1;
    private javax.swing.JLabel jLInstruccion2;
    private javax.swing.JLabel jLInstruccion3;
    private javax.swing.JLabel jLMensajeError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTxtEscribir;
    // End of variables declaration//GEN-END:variables
}
