/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Tipografias.Fuentes;

/**
 *
 * @author abiga
 */
public class ModoReto extends javax.swing.JFrame {

    /**
     * Creates new form ModoReto
     */
    
    Fuentes tipoFuente;
    
    public ModoReto() {
        initComponents();
        tipoFuente= new Fuentes();
        //Fuente texto de instrucciones
        mensajeInfo.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 30));
        mensajeInfo2.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 30));
        mensjaInfo3.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 30));
        MensajeError.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 25));
        //Fuente texto botones
        BSalir.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 40));
        BMenu.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        MensajeError = new javax.swing.JLabel();
        mensajeInfo = new javax.swing.JLabel();
        mensajeInfo2 = new javax.swing.JLabel();
        mensjaInfo3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        BMenu = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, 420, 60));
        getContentPane().add(MensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 700, 480, 60));

        mensajeInfo.setForeground(new java.awt.Color(0, 74, 173));
        mensajeInfo.setText("Traduce la palabra");
        getContentPane().add(mensajeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, -1, -1));

        mensajeInfo2.setForeground(new java.awt.Color(0, 74, 173));
        mensajeInfo2.setText("del meteorito al");
        getContentPane().add(mensajeInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, -1, -1));

        mensjaInfo3.setForeground(new java.awt.Color(0, 74, 173));
        mensjaInfo3.setText("inglés");
        getContentPane().add(mensjaInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 160, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BPausa60x60.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 70, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/corazon50x50.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 60));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 360, 30));

        BMenu.setForeground(new java.awt.Color(46, 27, 91));
        BMenu.setText("MENÚ");
        BMenu.setBorderPainted(false);
        BMenu.setContentAreaFilled(false);
        BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 710, 140, 60));

        BSalir.setForeground(new java.awt.Color(46, 27, 91));
        BSalir.setText("SALIR");
        BSalir.setBorderPainted(false);
        BSalir.setContentAreaFilled(false);
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 140, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonM_60x141.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 710, 140, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonS_60x142.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Modo reto 1400x800.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
        
        MenuMain obj = new MenuMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BSalirActionPerformed

    private void BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMenuActionPerformed
        // TODO add your handling code here:
        
        MenuMain obj = new MenuMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoReto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BMenu;
    private javax.swing.JButton BSalir;
    private javax.swing.JLabel MensajeError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mensajeInfo;
    private javax.swing.JLabel mensajeInfo2;
    private javax.swing.JLabel mensjaInfo3;
    // End of variables declaration//GEN-END:variables
}
