/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Tipografias.Fuentes;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author yired
 */
public class ModoClasico extends javax.swing.JFrame {

    /**
     * Creates new form ModoClasico
     */
    //fuentes
    Fuentes tipoFuente;
   
   //fondo frame
   FondoPanel fondo = new FondoPanel();
   
  
    public ModoClasico() {
        //fondo frame
        this.setContentPane(fondo);
        initComponents();
        
        //Fuentes
        tipoFuente = new Fuentes();
        
        //Barra puntaje
       
        
        //fuentes diseño
        
        btnsalir.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 40));
        btniniciar.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 40));
        //fuentes burbujas
        img1.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        img2.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        img3.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        img4.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        img5.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        img6.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 18));
        //fuente puntaje
        //BP.setFont(tipoFuente.fuente(tipoFuente.NINE, 0, 20));
    }
    
    
    //Barra puntaje
   
    public void fill(boolean status) {

    Thread t = new Thread(new Runnable() {
    @Override
    public void run() {
         try{
            int counter = 450;
                while(counter>=0 && status) {
                barra.setStringPainted(true);
                barra.setValue(counter);
                barra.setString(counter+" puntos");
                Thread.sleep(550);
                counter -=30;
                   // System.out.println(pg.getValue());
             }
        }catch(Exception ae){
            ae.printStackTrace();
    }
    }
});
    t.start(); 		
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btniniciar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnsonido = new javax.swing.JButton();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LCorazon = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 900));

        btniniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonMY_60x142.png"))); // NOI18N
        btniniciar.setText("INICIAR");
        btniniciar.setBorderPainted(false);
        btniniciar.setContentAreaFilled(false);
        btniniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonSalirY_60x142.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.setBorderPainted(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnsonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonsonido2.png"))); // NOI18N
        btnsonido.setBorderPainted(false);
        btnsonido.setContentAreaFilled(false);

        img1.setForeground(new java.awt.Color(255, 255, 255));
        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bubble1.png"))); // NOI18N
        img1.setText("Welcome!");
        img1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        img2.setBackground(new java.awt.Color(255, 255, 255));
        img2.setForeground(new java.awt.Color(255, 255, 255));
        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bubble2.png"))); // NOI18N
        img2.setText("Are you ready?");
        img2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        img3.setForeground(new java.awt.Color(255, 255, 255));
        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bubble1.png"))); // NOI18N
        img3.setText("Welcome!");
        img3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        img4.setForeground(new java.awt.Color(255, 255, 255));
        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bubble2.png"))); // NOI18N
        img4.setText("Are you ready?");
        img4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        img5.setForeground(new java.awt.Color(255, 255, 255));
        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bubble1.png"))); // NOI18N
        img5.setText("Welcome!");
        img5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        img6.setForeground(new java.awt.Color(255, 255, 255));
        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bubble2.png"))); // NOI18N
        img6.setText("Are you ready?");
        img6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LCorazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/corazon50x50.png"))); // NOI18N
        jPanel1.add(LCorazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        barra.setBackground(new java.awt.Color(0, 153, 255));
        barra.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        barra.setForeground(new java.awt.Color(255, 255, 255));
        barra.setMaximum(450);
        barra.setValue(450);
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 299, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(img4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(img5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsonido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
                            .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btniniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(580, 580, 580))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsonido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(img4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(img5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btniniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed
        // TODO add your handling code here:
        fill(true); 
        
    }//GEN-LAST:event_btniniciarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        
        MenuMain obj = new MenuMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoClasico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCorazon;
    private javax.swing.JProgressBar barra;
    private javax.swing.JButton btniniciar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsonido;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    //fondo frame
    class FondoPanel extends JPanel{
        
        private Image imagen;
        
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Img/ModoClasico1400x1800.png")).getImage();
            g.drawImage(imagen, 0, 0, this.getWidth(), this.getHeight(), this);
            setOpaque(false);
            super.paint(g);
                        
        }
        
    }


}
