/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Tipografias.Fuentes;

/**
 *
 * @author yired
 */
public class ModoClasico extends javax.swing.JFrame {

    /**
     * Creates new form ModoClasico
     */
    Fuentes tipoFuente;
    public ModoClasico() {
        initComponents();
        tipoFuente = new Fuentes();
        //cuerpo = new Fuentes();
        LTexto1.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 17));
        LTexto2.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 17));
        LTexto3.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTexto1 = new javax.swing.JLabel();
        LTexto2 = new javax.swing.JLabel();
        LTexto3 = new javax.swing.JLabel();
        BLetraSalir = new javax.swing.JButton();
        BLetraMenu = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        LCorazon = new javax.swing.JLabel();
        BSonido = new javax.swing.JButton();
        BPausa = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        LFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LTexto1.setForeground(new java.awt.Color(0, 74, 173));
        LTexto1.setText("Presta atención al");
        getContentPane().add(LTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 180, 40));

        LTexto2.setForeground(new java.awt.Color(0, 74, 173));
        LTexto2.setText("audio y selecciona");
        getContentPane().add(LTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 180, 30));

        LTexto3.setForeground(new java.awt.Color(0, 74, 173));
        LTexto3.setText("la palabra correcta");
        getContentPane().add(LTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 180, 20));

        BLetraSalir.setForeground(new java.awt.Color(31, 19, 71));
        BLetraSalir.setText("Salir");
        BLetraSalir.setBorderPainted(false);
        BLetraSalir.setContentAreaFilled(false);
        getContentPane().add(BLetraSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 413, 60, 30));

        BLetraMenu.setForeground(new java.awt.Color(31, 19, 71));
        BLetraMenu.setText("Menú");
        BLetraMenu.setBorderPainted(false);
        BLetraMenu.setContentAreaFilled(false);
        BLetraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLetraMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BLetraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, 20));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton4.png"))); // NOI18N
        BotonMenu.setBorderPainted(false);
        BotonMenu.setContentAreaFilled(false);
        getContentPane().add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 100, 40));

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton3.png"))); // NOI18N
        BotonSalir.setBorderPainted(false);
        BotonSalir.setContentAreaFilled(false);
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 80, 40));

        LCorazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/corazon.png"))); // NOI18N
        getContentPane().add(LCorazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        BSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonsonido2.png"))); // NOI18N
        BSonido.setBorderPainted(false);
        BSonido.setContentAreaFilled(false);
        getContentPane().add(BSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 80, 60));

        BPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonpausa1.png"))); // NOI18N
        BPausa.setBorderPainted(false);
        BPausa.setContentAreaFilled(false);
        getContentPane().add(BPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 70, -1));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        LFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Modo clasico.png"))); // NOI18N
        getContentPane().add(LFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 457));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BLetraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLetraMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BLetraMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoClasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoClasico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLetraMenu;
    private javax.swing.JButton BLetraSalir;
    private javax.swing.JButton BPausa;
    private javax.swing.JButton BSonido;
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LCorazon;
    private javax.swing.JLabel LFondo;
    private javax.swing.JLabel LTexto1;
    private javax.swing.JLabel LTexto2;
    private javax.swing.JLabel LTexto3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
