/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Tipografias.Fuentes;

/**
 *
 * @author EMmanuel
 */
public class StartAddWord extends javax.swing.JFrame {

    /**
     * Creates new form InicioMain
     */
    Fuentes tipoFuente;

    public StartAddWord() {
        initComponents();
        tipoFuente = new Fuentes();
        //cuerpo = new Fuentes();
        Subtitulo.setFont(tipoFuente.fuente(tipoFuente.CHERRY, 0, 45));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subtitulo = new javax.swing.JLabel();
        Español = new javax.swing.JLabel();
        Ingles = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BComenzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Subtitulo.setForeground(new java.awt.Color(0, 74, 173));
        Subtitulo.setText("Ingresa tus palabras aquí");
        Subtitulo.setName(""); // NOI18N
        getContentPane().add(Subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        Español.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        Español.setForeground(new java.awt.Color(23, 159, 235));
        Español.setText("Español");
        getContentPane().add(Español, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        Ingles.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        Ingles.setForeground(new java.awt.Color(23, 159, 235));
        Ingles.setText("Inglés");
        getContentPane().add(Ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("+");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 50, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("+");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 50, 50));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 250, 50));

        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconcontrolinicio5.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 70));

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("COMENZAR");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 100, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 210, 120));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 300, 190, 120));

        BComenzar.setBackground(new java.awt.Color(0, 0, 102));
        BComenzar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BComenzar.setForeground(new java.awt.Color(255, 255, 255));
        BComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton2.png"))); // NOI18N
        BComenzar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BComenzar.setBorderPainted(false);
        BComenzar.setContentAreaFilled(false);
        BComenzar.setMargin(new java.awt.Insets(5, 10, 5, 10));
        BComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(BComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Inicio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void BComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BComenzarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartAddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartAddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartAddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartAddWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartAddWord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComenzar;
    private javax.swing.JLabel Español;
    private javax.swing.JLabel Ingles;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
